### ISSUE TITLE
Google Analytics not working on demo site

### ISSUE THREAD

**Issue by lederer** [azavea/react-showtime#25]
The demo site refuses to load Google Analytics:

> Refused to load the script 'https://www.googletagmanager.com/gtag/js?id=UA-970854-41' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

This may be helpful: https://developers.google.com/tag-manager/web/csp

**Comment by ColeKettler** [comment]
Fixed by #27.
